<td class="hp"><a href="#" onmouseover="HIn('IP1')" onmouseout="HOut('IP1')"><span class="hpblock" id="IP1"><span class="hptitle">Edit device IP Address</span><span class="hpcontent"><span class="hpsection">If 'Manual' enter an IP address in the form xxx.xxx.xxx.xxx (e.g. 192.168.1.48).  If you are unsure of what IP Address to use please contact your Network Administrator.</span></span></a></td>
</tr>
<tr>
<td title="">Subnet Mask: </td><