<td class="hp"><a href="#" onmouseover="HIn('IP3')" onmouseout="HOut('IP3')"><span class="hpblock" id="IP3"><span class="hptitle">Edit device Default Gateway</span><span class="hpcontent"><span class="hpsection">If 'Manual' enter the IP Address of the gateway (e.g. as used by the NTP feature) in the form xxx.xxx.xxx.xxx (e.g. 192.168.1.1).</span></span></a></td>
</tr>
<tr>
<td title="">DNS Server: </td>
<