<div id="wrapper">
<div id="header">
	<div id="logo">
	  <img src="images/cb_logo.gif" />
	</div>
	<div id="header_text">
		<h4> Zone Protector </h4>
		<p>Model: CB-ZP-AMT9900</p> 
	</div>
	<div id="user_logo">
	  <ul>
		<li><a href="wStart.htm?wStart=1" class="spWiz"><br /><span>Settings Wizard</span></a></li>
		<li style="border:none;"><a href="index.htm?logout=1" class="spLogout"><br /><br /><br /><span id="span_logout">Logout</span></a></li>
	  </ul>	
	</div>
	<div style="clear:both;"></div>
</div>
~