<td class="hp"><a href="#" onmouseover="HIn('hsPort')" onmouseout="HOut('hsPort')"><span class="hpblock" id="hsPort"><span class="hptitle">Zone Manager server port number</span><span class="hpcontent"><span class="hpsection">This field should display the Port Number of the Zone Manager - please refer to your Zone Manager documentation.</span></span></a></td>
</tr>
<tr>
<td>License Expiry Date: </td>
